name: Build AMI using Packer

on:
  pull_request:
    branches:
      - main

jobs:
  build_ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          cd ./server
          touch .env
          echo SERVER_PORT=${{ vars.SERVER_PORT }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_URI=${{ secrets.POSTGRES_URI }} >> .env
          echo FILEPATH=${{ vars.FILEPATH }} >> .env

      - name: Zip Folder
        run: zip -r webapp.zip .

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/
        shell: bash

      - name: Build AMI
        run: |
          cd deployment/ami
          packer init ./
          packer build -var "aws_access_key=AKIATV62B2TCK4ALTL4H" -var "aws_secret_access_key=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" .