name: Build AMI using Packer

on:
  pull_request:
    type:
      - closed
    branches:
      - main

jobs:
  db_health_check:
    if: github.event.pull_request.merged == true
    name: db_health_check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create env file
        run: |
          cd ./server
          touch .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_URI=${{ secrets.POSTGRES_URI }} >> .env
          echo FILEPATH=${{ secrets.FILEPATH }} >> .env

      - name: Install and run PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql
          sudo service postgresql start

      - name: Create PostgreSQL Database
        run: |
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.POSTGRES_DB }} OWNER ${{ secrets.POSTGRES_USER }};"
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD ${{ secrets.POSTGRES_PASSWORD }};"

      - name: Install Dependencies
        run: |
          cd ./database && npm install
          cd ../server && npm install

      - name: Run Integration Tests
        run: |
          pwd
          cd ./server && npm run test

  build_ami:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          cd ./server
          touch .env
          echo SERVER_PORT=${{ vars.SERVER_PORT }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_URI=${{ secrets.POSTGRES_URI }} >> .env
          echo FILEPATH=${{ vars.FILEPATH }} >> .env

      - name: Zip Folder
        run: zip -r webapp.zip .

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin/
        shell: bash

      - name: Build AMI
        run: |
          cd deployment/ami
          packer init ./
          packer build \
            -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
            -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -var "source_ami=${{ vars.SOURCE_AMI }}" \
            -var "ami_region=${{ vars.AMI_REGION }}" \
            -var "zip_file_path=${{ vars.APP_ZIP_PATH }}" .
