name: Integration Test

on:
  pull_request:
    branches:
      - main

jobs:
  db_health_check:
    name: db_health_check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create env file
        run: |
          cd ./server
          touch .env.test
          echo SERVER_PORT=${{ vars.SERVER_PORT }} >> .env.test
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_URI=${{ secrets.POSTGRES_URI }} >> .env
          echo FILEPATH=${{ secrets.FILEPATH }} >> .env

      - name: Install and run PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql
          sudo service postgresql start

      - name: Create PostgreSQL Database
        run: |
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.POSTGRES_DB }} OWNER ${{ secrets.POSTGRES_USER }};"

      - name: Change password
        run: |
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD ${{ secrets.POSTGRES_PASSWORD }};"

      - name: Install Dependencies
        run: |
          cd ./database && npm install
          cd ../server && npm install

      - name: Run Integration Tests
        run: |
          pwd
          cd ./server && npm run test
